import { EventEmitter } from "eventemitter3";
import { ConfigAds, ConfigAdsManager, IAdsManager } from "./ads.interface";
import { google } from ".";
export default class AdsManager extends EventEmitter implements IAdsManager {
    private _name;
    private static _instance;
    private _idVideo;
    private _idContainer;
    private _videoElement;
    private _containerElement;
    private imaSdk;
    private imaAdsLoader;
    private imaAdsManager;
    private _timerPlayer;
    private _timerStartLoad;
    private _timerBuffering;
    private _showAds_;
    private _currentTime;
    private _skipTime;
    static getInstance(config?: ConfigAdsManager): AdsManager;
    static clear(): void;
    constructor(config?: ConfigAdsManager);
    private init;
    private destroy;
    clearAds(): void;
    private resetAds;
    skipAd(): void;
    getImaSdk(): typeof google.ima | undefined;
    getImaAdsLoader(): google.ima.AdsLoader | undefined;
    getImaAdsManager(): google.ima.AdsManager | undefined;
    setVideoId(videoId: string): void;
    getVideoElement(): HTMLVideoElement | null;
    setContainerId(containerId: string): void;
    getContainerElement(): HTMLElement | null;
    loadAds(config: ConfigAds): void;
    private removeChild;
    private settingAdsLoader;
    private onAdsManagerLoaded;
    private onAdLoaded;
    private onAdError;
    private _clearTimerBuffer;
    private _clearTimerPlayer;
    private _clearTimerStartLoad;
    private onContentResumeRequested;
    private onContentPauseRequested;
}
